package com.wxbus.daomain;

import java.util.Date;

public class DriverBusRoute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.d_b_r_id
     *
     * @mbggenerated
     */
    private Integer dBRId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.driver_id
     *
     * @mbggenerated
     */
    private String driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.bus_id
     *
     * @mbggenerated
     */
    private String busId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.route_id
     *
     * @mbggenerated
     */
    private Integer routeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.dirver_time
     *
     * @mbggenerated
     */
    private Date dirverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.bus_time
     *
     * @mbggenerated
     */
    private Date busTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.route_status
     *
     * @mbggenerated
     */
    private Integer routeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.driver_out_time
     *
     * @mbggenerated
     */
    private Date driverOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_bus_route.driver_status
     *
     * @mbggenerated
     */
    private Integer driverStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.d_b_r_id
     *
     * @return the value of driver_bus_route.d_b_r_id
     *
     * @mbggenerated
     */
    public Integer getdBRId() {
        return dBRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.d_b_r_id
     *
     * @param dBRId the value for driver_bus_route.d_b_r_id
     *
     * @mbggenerated
     */
    public void setdBRId(Integer dBRId) {
        this.dBRId = dBRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.driver_id
     *
     * @return the value of driver_bus_route.driver_id
     *
     * @mbggenerated
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.driver_id
     *
     * @param driverId the value for driver_bus_route.driver_id
     *
     * @mbggenerated
     */
    public void setDriverId(String driverId) {
        this.driverId = driverId == null ? null : driverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.bus_id
     *
     * @return the value of driver_bus_route.bus_id
     *
     * @mbggenerated
     */
    public String getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.bus_id
     *
     * @param busId the value for driver_bus_route.bus_id
     *
     * @mbggenerated
     */
    public void setBusId(String busId) {
        this.busId = busId == null ? null : busId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.route_id
     *
     * @return the value of driver_bus_route.route_id
     *
     * @mbggenerated
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.route_id
     *
     * @param routeId the value for driver_bus_route.route_id
     *
     * @mbggenerated
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.dirver_time
     *
     * @return the value of driver_bus_route.dirver_time
     *
     * @mbggenerated
     */
    public Date getDirverTime() {
        return dirverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.dirver_time
     *
     * @param dirverTime the value for driver_bus_route.dirver_time
     *
     * @mbggenerated
     */
    public void setDirverTime(Date dirverTime) {
        this.dirverTime = dirverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.bus_time
     *
     * @return the value of driver_bus_route.bus_time
     *
     * @mbggenerated
     */
    public Date getBusTime() {
        return busTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.bus_time
     *
     * @param busTime the value for driver_bus_route.bus_time
     *
     * @mbggenerated
     */
    public void setBusTime(Date busTime) {
        this.busTime = busTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.route_status
     *
     * @return the value of driver_bus_route.route_status
     *
     * @mbggenerated
     */
    public Integer getRouteStatus() {
        return routeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.route_status
     *
     * @param routeStatus the value for driver_bus_route.route_status
     *
     * @mbggenerated
     */
    public void setRouteStatus(Integer routeStatus) {
        this.routeStatus = routeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.driver_out_time
     *
     * @return the value of driver_bus_route.driver_out_time
     *
     * @mbggenerated
     */
    public Date getDriverOutTime() {
        return driverOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.driver_out_time
     *
     * @param driverOutTime the value for driver_bus_route.driver_out_time
     *
     * @mbggenerated
     */
    public void setDriverOutTime(Date driverOutTime) {
        this.driverOutTime = driverOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_bus_route.driver_status
     *
     * @return the value of driver_bus_route.driver_status
     *
     * @mbggenerated
     */
    public Integer getDriverStatus() {
        return driverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_bus_route.driver_status
     *
     * @param driverStatus the value for driver_bus_route.driver_status
     *
     * @mbggenerated
     */
    public void setDriverStatus(Integer driverStatus) {
        this.driverStatus = driverStatus;
    }
}