package com.wxbus.daomain;

import java.util.Date;

public class Driver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_id
     *
     * @mbggenerated
     */
    private String driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_name
     *
     * @mbggenerated
     */
    private String driverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.deiver_gender
     *
     * @mbggenerated
     */
    private String deiverGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_password
     *
     * @mbggenerated
     */
    private String driverPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_avater
     *
     * @mbggenerated
     */
    private String driverAvater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_citizenship
     *
     * @mbggenerated
     */
    private String driverCitizenship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.drive_id
     *
     * @mbggenerated
     */
    private String driveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_nationality
     *
     * @mbggenerated
     */
    private String driverNationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_address
     *
     * @mbggenerated
     */
    private String driverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.first_getlicence
     *
     * @mbggenerated
     */
    private Date firstGetlicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_mobile
     *
     * @mbggenerated
     */
    private String driverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.register_ip
     *
     * @mbggenerated
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.last_login_ip
     *
     * @mbggenerated
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driving_type
     *
     * @mbggenerated
     */
    private String drivingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_mark
     *
     * @mbggenerated
     */
    private Integer driverMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_status
     *
     * @mbggenerated
     */
    private Integer driverStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_id
     *
     * @return the value of driver.driver_id
     *
     * @mbggenerated
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_id
     *
     * @param driverId the value for driver.driver_id
     *
     * @mbggenerated
     */
    public void setDriverId(String driverId) {
        this.driverId = driverId == null ? null : driverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_name
     *
     * @return the value of driver.driver_name
     *
     * @mbggenerated
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_name
     *
     * @param driverName the value for driver.driver_name
     *
     * @mbggenerated
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName == null ? null : driverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.deiver_gender
     *
     * @return the value of driver.deiver_gender
     *
     * @mbggenerated
     */
    public String getDeiverGender() {
        return deiverGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.deiver_gender
     *
     * @param deiverGender the value for driver.deiver_gender
     *
     * @mbggenerated
     */
    public void setDeiverGender(String deiverGender) {
        this.deiverGender = deiverGender == null ? null : deiverGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_password
     *
     * @return the value of driver.driver_password
     *
     * @mbggenerated
     */
    public String getDriverPassword() {
        return driverPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_password
     *
     * @param driverPassword the value for driver.driver_password
     *
     * @mbggenerated
     */
    public void setDriverPassword(String driverPassword) {
        this.driverPassword = driverPassword == null ? null : driverPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_avater
     *
     * @return the value of driver.driver_avater
     *
     * @mbggenerated
     */
    public String getDriverAvater() {
        return driverAvater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_avater
     *
     * @param driverAvater the value for driver.driver_avater
     *
     * @mbggenerated
     */
    public void setDriverAvater(String driverAvater) {
        this.driverAvater = driverAvater == null ? null : driverAvater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_citizenship
     *
     * @return the value of driver.driver_citizenship
     *
     * @mbggenerated
     */
    public String getDriverCitizenship() {
        return driverCitizenship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_citizenship
     *
     * @param driverCitizenship the value for driver.driver_citizenship
     *
     * @mbggenerated
     */
    public void setDriverCitizenship(String driverCitizenship) {
        this.driverCitizenship = driverCitizenship == null ? null : driverCitizenship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.drive_id
     *
     * @return the value of driver.drive_id
     *
     * @mbggenerated
     */
    public String getDriveId() {
        return driveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.drive_id
     *
     * @param driveId the value for driver.drive_id
     *
     * @mbggenerated
     */
    public void setDriveId(String driveId) {
        this.driveId = driveId == null ? null : driveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_nationality
     *
     * @return the value of driver.driver_nationality
     *
     * @mbggenerated
     */
    public String getDriverNationality() {
        return driverNationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_nationality
     *
     * @param driverNationality the value for driver.driver_nationality
     *
     * @mbggenerated
     */
    public void setDriverNationality(String driverNationality) {
        this.driverNationality = driverNationality == null ? null : driverNationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_address
     *
     * @return the value of driver.driver_address
     *
     * @mbggenerated
     */
    public String getDriverAddress() {
        return driverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_address
     *
     * @param driverAddress the value for driver.driver_address
     *
     * @mbggenerated
     */
    public void setDriverAddress(String driverAddress) {
        this.driverAddress = driverAddress == null ? null : driverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.birthday
     *
     * @return the value of driver.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.birthday
     *
     * @param birthday the value for driver.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.first_getlicence
     *
     * @return the value of driver.first_getlicence
     *
     * @mbggenerated
     */
    public Date getFirstGetlicence() {
        return firstGetlicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.first_getlicence
     *
     * @param firstGetlicence the value for driver.first_getlicence
     *
     * @mbggenerated
     */
    public void setFirstGetlicence(Date firstGetlicence) {
        this.firstGetlicence = firstGetlicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_mobile
     *
     * @return the value of driver.driver_mobile
     *
     * @mbggenerated
     */
    public String getDriverMobile() {
        return driverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_mobile
     *
     * @param driverMobile the value for driver.driver_mobile
     *
     * @mbggenerated
     */
    public void setDriverMobile(String driverMobile) {
        this.driverMobile = driverMobile == null ? null : driverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.register_ip
     *
     * @return the value of driver.register_ip
     *
     * @mbggenerated
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.register_ip
     *
     * @param registerIp the value for driver.register_ip
     *
     * @mbggenerated
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.register_time
     *
     * @return the value of driver.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.register_time
     *
     * @param registerTime the value for driver.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.last_login_time
     *
     * @return the value of driver.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.last_login_time
     *
     * @param lastLoginTime the value for driver.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.last_login_ip
     *
     * @return the value of driver.last_login_ip
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.last_login_ip
     *
     * @param lastLoginIp the value for driver.last_login_ip
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driving_type
     *
     * @return the value of driver.driving_type
     *
     * @mbggenerated
     */
    public String getDrivingType() {
        return drivingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driving_type
     *
     * @param drivingType the value for driver.driving_type
     *
     * @mbggenerated
     */
    public void setDrivingType(String drivingType) {
        this.drivingType = drivingType == null ? null : drivingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.integral
     *
     * @return the value of driver.integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.integral
     *
     * @param integral the value for driver.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_mark
     *
     * @return the value of driver.driver_mark
     *
     * @mbggenerated
     */
    public Integer getDriverMark() {
        return driverMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_mark
     *
     * @param driverMark the value for driver.driver_mark
     *
     * @mbggenerated
     */
    public void setDriverMark(Integer driverMark) {
        this.driverMark = driverMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_status
     *
     * @return the value of driver.driver_status
     *
     * @mbggenerated
     */
    public Integer getDriverStatus() {
        return driverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_status
     *
     * @param driverStatus the value for driver.driver_status
     *
     * @mbggenerated
     */
    public void setDriverStatus(Integer driverStatus) {
        this.driverStatus = driverStatus;
    }
}