package com.wxbus.daomain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PassengerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table passenger
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table passenger
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table passenger
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public PassengerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table passenger
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipIsNull() {
            addCriterion("passenger_citizenship is null");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipIsNotNull() {
            addCriterion("passenger_citizenship is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipEqualTo(String value) {
            addCriterion("passenger_citizenship =", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipNotEqualTo(String value) {
            addCriterion("passenger_citizenship <>", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipGreaterThan(String value) {
            addCriterion("passenger_citizenship >", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipGreaterThanOrEqualTo(String value) {
            addCriterion("passenger_citizenship >=", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipLessThan(String value) {
            addCriterion("passenger_citizenship <", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipLessThanOrEqualTo(String value) {
            addCriterion("passenger_citizenship <=", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipLike(String value) {
            addCriterion("passenger_citizenship like", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipNotLike(String value) {
            addCriterion("passenger_citizenship not like", value, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipIn(List<String> values) {
            addCriterion("passenger_citizenship in", values, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipNotIn(List<String> values) {
            addCriterion("passenger_citizenship not in", values, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipBetween(String value1, String value2) {
            addCriterion("passenger_citizenship between", value1, value2, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerCitizenshipNotBetween(String value1, String value2) {
            addCriterion("passenger_citizenship not between", value1, value2, "passengerCitizenship");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameIsNull() {
            addCriterion("passenger_nickname is null");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameIsNotNull() {
            addCriterion("passenger_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameEqualTo(String value) {
            addCriterion("passenger_nickname =", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameNotEqualTo(String value) {
            addCriterion("passenger_nickname <>", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameGreaterThan(String value) {
            addCriterion("passenger_nickname >", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("passenger_nickname >=", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameLessThan(String value) {
            addCriterion("passenger_nickname <", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameLessThanOrEqualTo(String value) {
            addCriterion("passenger_nickname <=", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameLike(String value) {
            addCriterion("passenger_nickname like", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameNotLike(String value) {
            addCriterion("passenger_nickname not like", value, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameIn(List<String> values) {
            addCriterion("passenger_nickname in", values, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameNotIn(List<String> values) {
            addCriterion("passenger_nickname not in", values, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameBetween(String value1, String value2) {
            addCriterion("passenger_nickname between", value1, value2, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNicknameNotBetween(String value1, String value2) {
            addCriterion("passenger_nickname not between", value1, value2, "passengerNickname");
            return (Criteria) this;
        }

        public Criteria andPassengerNameIsNull() {
            addCriterion("passenger_name is null");
            return (Criteria) this;
        }

        public Criteria andPassengerNameIsNotNull() {
            addCriterion("passenger_name is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerNameEqualTo(String value) {
            addCriterion("passenger_name =", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameNotEqualTo(String value) {
            addCriterion("passenger_name <>", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameGreaterThan(String value) {
            addCriterion("passenger_name >", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameGreaterThanOrEqualTo(String value) {
            addCriterion("passenger_name >=", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameLessThan(String value) {
            addCriterion("passenger_name <", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameLessThanOrEqualTo(String value) {
            addCriterion("passenger_name <=", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameLike(String value) {
            addCriterion("passenger_name like", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameNotLike(String value) {
            addCriterion("passenger_name not like", value, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameIn(List<String> values) {
            addCriterion("passenger_name in", values, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameNotIn(List<String> values) {
            addCriterion("passenger_name not in", values, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameBetween(String value1, String value2) {
            addCriterion("passenger_name between", value1, value2, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerNameNotBetween(String value1, String value2) {
            addCriterion("passenger_name not between", value1, value2, "passengerName");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordIsNull() {
            addCriterion("passenger_password is null");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordIsNotNull() {
            addCriterion("passenger_password is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordEqualTo(String value) {
            addCriterion("passenger_password =", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordNotEqualTo(String value) {
            addCriterion("passenger_password <>", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordGreaterThan(String value) {
            addCriterion("passenger_password >", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("passenger_password >=", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordLessThan(String value) {
            addCriterion("passenger_password <", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordLessThanOrEqualTo(String value) {
            addCriterion("passenger_password <=", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordLike(String value) {
            addCriterion("passenger_password like", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordNotLike(String value) {
            addCriterion("passenger_password not like", value, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordIn(List<String> values) {
            addCriterion("passenger_password in", values, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordNotIn(List<String> values) {
            addCriterion("passenger_password not in", values, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordBetween(String value1, String value2) {
            addCriterion("passenger_password between", value1, value2, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerPasswordNotBetween(String value1, String value2) {
            addCriterion("passenger_password not between", value1, value2, "passengerPassword");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderIsNull() {
            addCriterion("passenger_gender is null");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderIsNotNull() {
            addCriterion("passenger_gender is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderEqualTo(String value) {
            addCriterion("passenger_gender =", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderNotEqualTo(String value) {
            addCriterion("passenger_gender <>", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderGreaterThan(String value) {
            addCriterion("passenger_gender >", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderGreaterThanOrEqualTo(String value) {
            addCriterion("passenger_gender >=", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderLessThan(String value) {
            addCriterion("passenger_gender <", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderLessThanOrEqualTo(String value) {
            addCriterion("passenger_gender <=", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderLike(String value) {
            addCriterion("passenger_gender like", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderNotLike(String value) {
            addCriterion("passenger_gender not like", value, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderIn(List<String> values) {
            addCriterion("passenger_gender in", values, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderNotIn(List<String> values) {
            addCriterion("passenger_gender not in", values, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderBetween(String value1, String value2) {
            addCriterion("passenger_gender between", value1, value2, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerGenderNotBetween(String value1, String value2) {
            addCriterion("passenger_gender not between", value1, value2, "passengerGender");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayIsNull() {
            addCriterion("passenger_birthday is null");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayIsNotNull() {
            addCriterion("passenger_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("passenger_birthday =", value, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("passenger_birthday <>", value, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("passenger_birthday >", value, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("passenger_birthday >=", value, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("passenger_birthday <", value, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("passenger_birthday <=", value, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("passenger_birthday in", values, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("passenger_birthday not in", values, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("passenger_birthday between", value1, value2, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andPassengerBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("passenger_birthday not between", value1, value2, "passengerBirthday");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("last_login_time is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("last_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("last_login_time =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("last_login_time <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("last_login_time >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login_time >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("last_login_time <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_login_time <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("last_login_time in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("last_login_time not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("last_login_time between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNull() {
            addCriterion("last_login_ip is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNotNull() {
            addCriterion("last_login_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpEqualTo(String value) {
            addCriterion("last_login_ip =", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotEqualTo(String value) {
            addCriterion("last_login_ip <>", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThan(String value) {
            addCriterion("last_login_ip >", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("last_login_ip >=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThan(String value) {
            addCriterion("last_login_ip <", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThanOrEqualTo(String value) {
            addCriterion("last_login_ip <=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLike(String value) {
            addCriterion("last_login_ip like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotLike(String value) {
            addCriterion("last_login_ip not like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIn(List<String> values) {
            addCriterion("last_login_ip in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotIn(List<String> values) {
            addCriterion("last_login_ip not in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpBetween(String value1, String value2) {
            addCriterion("last_login_ip between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotBetween(String value1, String value2) {
            addCriterion("last_login_ip not between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileIsNull() {
            addCriterion("passenger_mobile is null");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileIsNotNull() {
            addCriterion("passenger_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileEqualTo(String value) {
            addCriterion("passenger_mobile =", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileNotEqualTo(String value) {
            addCriterion("passenger_mobile <>", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileGreaterThan(String value) {
            addCriterion("passenger_mobile >", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileGreaterThanOrEqualTo(String value) {
            addCriterion("passenger_mobile >=", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileLessThan(String value) {
            addCriterion("passenger_mobile <", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileLessThanOrEqualTo(String value) {
            addCriterion("passenger_mobile <=", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileLike(String value) {
            addCriterion("passenger_mobile like", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileNotLike(String value) {
            addCriterion("passenger_mobile not like", value, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileIn(List<String> values) {
            addCriterion("passenger_mobile in", values, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileNotIn(List<String> values) {
            addCriterion("passenger_mobile not in", values, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileBetween(String value1, String value2) {
            addCriterion("passenger_mobile between", value1, value2, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerMobileNotBetween(String value1, String value2) {
            addCriterion("passenger_mobile not between", value1, value2, "passengerMobile");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterIsNull() {
            addCriterion("passenger_avater is null");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterIsNotNull() {
            addCriterion("passenger_avater is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterEqualTo(String value) {
            addCriterion("passenger_avater =", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterNotEqualTo(String value) {
            addCriterion("passenger_avater <>", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterGreaterThan(String value) {
            addCriterion("passenger_avater >", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterGreaterThanOrEqualTo(String value) {
            addCriterion("passenger_avater >=", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterLessThan(String value) {
            addCriterion("passenger_avater <", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterLessThanOrEqualTo(String value) {
            addCriterion("passenger_avater <=", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterLike(String value) {
            addCriterion("passenger_avater like", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterNotLike(String value) {
            addCriterion("passenger_avater not like", value, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterIn(List<String> values) {
            addCriterion("passenger_avater in", values, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterNotIn(List<String> values) {
            addCriterion("passenger_avater not in", values, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterBetween(String value1, String value2) {
            addCriterion("passenger_avater between", value1, value2, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andPassengerAvaterNotBetween(String value1, String value2) {
            addCriterion("passenger_avater not between", value1, value2, "passengerAvater");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidIsNull() {
            addCriterion("weixin_openid is null");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidIsNotNull() {
            addCriterion("weixin_openid is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidEqualTo(String value) {
            addCriterion("weixin_openid =", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidNotEqualTo(String value) {
            addCriterion("weixin_openid <>", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidGreaterThan(String value) {
            addCriterion("weixin_openid >", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("weixin_openid >=", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidLessThan(String value) {
            addCriterion("weixin_openid <", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidLessThanOrEqualTo(String value) {
            addCriterion("weixin_openid <=", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidLike(String value) {
            addCriterion("weixin_openid like", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidNotLike(String value) {
            addCriterion("weixin_openid not like", value, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidIn(List<String> values) {
            addCriterion("weixin_openid in", values, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidNotIn(List<String> values) {
            addCriterion("weixin_openid not in", values, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidBetween(String value1, String value2) {
            addCriterion("weixin_openid between", value1, value2, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andWeixinOpenidNotBetween(String value1, String value2) {
            addCriterion("weixin_openid not between", value1, value2, "weixinOpenid");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusIsNull() {
            addCriterion("passenger_status is null");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusIsNotNull() {
            addCriterion("passenger_status is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusEqualTo(Integer value) {
            addCriterion("passenger_status =", value, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusNotEqualTo(Integer value) {
            addCriterion("passenger_status <>", value, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusGreaterThan(Integer value) {
            addCriterion("passenger_status >", value, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("passenger_status >=", value, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusLessThan(Integer value) {
            addCriterion("passenger_status <", value, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusLessThanOrEqualTo(Integer value) {
            addCriterion("passenger_status <=", value, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusIn(List<Integer> values) {
            addCriterion("passenger_status in", values, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusNotIn(List<Integer> values) {
            addCriterion("passenger_status not in", values, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusBetween(Integer value1, Integer value2) {
            addCriterion("passenger_status between", value1, value2, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("passenger_status not between", value1, value2, "passengerStatus");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeIsNull() {
            addCriterion("fist_login_time is null");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeIsNotNull() {
            addCriterion("fist_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeEqualTo(Date value) {
            addCriterion("fist_login_time =", value, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeNotEqualTo(Date value) {
            addCriterion("fist_login_time <>", value, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeGreaterThan(Date value) {
            addCriterion("fist_login_time >", value, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fist_login_time >=", value, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeLessThan(Date value) {
            addCriterion("fist_login_time <", value, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("fist_login_time <=", value, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeIn(List<Date> values) {
            addCriterion("fist_login_time in", values, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeNotIn(List<Date> values) {
            addCriterion("fist_login_time not in", values, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeBetween(Date value1, Date value2) {
            addCriterion("fist_login_time between", value1, value2, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("fist_login_time not between", value1, value2, "fistLoginTime");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpIsNull() {
            addCriterion("fist_login_ip is null");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpIsNotNull() {
            addCriterion("fist_login_ip is not null");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpEqualTo(String value) {
            addCriterion("fist_login_ip =", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpNotEqualTo(String value) {
            addCriterion("fist_login_ip <>", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpGreaterThan(String value) {
            addCriterion("fist_login_ip >", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("fist_login_ip >=", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpLessThan(String value) {
            addCriterion("fist_login_ip <", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpLessThanOrEqualTo(String value) {
            addCriterion("fist_login_ip <=", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpLike(String value) {
            addCriterion("fist_login_ip like", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpNotLike(String value) {
            addCriterion("fist_login_ip not like", value, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpIn(List<String> values) {
            addCriterion("fist_login_ip in", values, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpNotIn(List<String> values) {
            addCriterion("fist_login_ip not in", values, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpBetween(String value1, String value2) {
            addCriterion("fist_login_ip between", value1, value2, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andFistLoginIpNotBetween(String value1, String value2) {
            addCriterion("fist_login_ip not between", value1, value2, "fistLoginIp");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table passenger
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table passenger
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}