package com.wxbus.daomain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RouteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table route
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table route
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table route
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public RouteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table route
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRouteIdIsNull() {
            addCriterion("route_id is null");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNotNull() {
            addCriterion("route_id is not null");
            return (Criteria) this;
        }

        public Criteria andRouteIdEqualTo(Integer value) {
            addCriterion("route_id =", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotEqualTo(Integer value) {
            addCriterion("route_id <>", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThan(Integer value) {
            addCriterion("route_id >", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_id >=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThan(Integer value) {
            addCriterion("route_id <", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThanOrEqualTo(Integer value) {
            addCriterion("route_id <=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIn(List<Integer> values) {
            addCriterion("route_id in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotIn(List<Integer> values) {
            addCriterion("route_id not in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdBetween(Integer value1, Integer value2) {
            addCriterion("route_id between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("route_id not between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIsNull() {
            addCriterion("creat_user is null");
            return (Criteria) this;
        }

        public Criteria andCreatUserIsNotNull() {
            addCriterion("creat_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreatUserEqualTo(String value) {
            addCriterion("creat_user =", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserNotEqualTo(String value) {
            addCriterion("creat_user <>", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserGreaterThan(String value) {
            addCriterion("creat_user >", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserGreaterThanOrEqualTo(String value) {
            addCriterion("creat_user >=", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserLessThan(String value) {
            addCriterion("creat_user <", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserLessThanOrEqualTo(String value) {
            addCriterion("creat_user <=", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserLike(String value) {
            addCriterion("creat_user like", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserNotLike(String value) {
            addCriterion("creat_user not like", value, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserIn(List<String> values) {
            addCriterion("creat_user in", values, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserNotIn(List<String> values) {
            addCriterion("creat_user not in", values, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserBetween(String value1, String value2) {
            addCriterion("creat_user between", value1, value2, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatUserNotBetween(String value1, String value2) {
            addCriterion("creat_user not between", value1, value2, "creatUser");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creat_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creat_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("creat_time =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("creat_time <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("creat_time >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creat_time >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("creat_time <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("creat_time <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("creat_time in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("creat_time not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("creat_time between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("creat_time not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andRouteStatusIsNull() {
            addCriterion("route_status is null");
            return (Criteria) this;
        }

        public Criteria andRouteStatusIsNotNull() {
            addCriterion("route_status is not null");
            return (Criteria) this;
        }

        public Criteria andRouteStatusEqualTo(Integer value) {
            addCriterion("route_status =", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusNotEqualTo(Integer value) {
            addCriterion("route_status <>", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusGreaterThan(Integer value) {
            addCriterion("route_status >", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_status >=", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusLessThan(Integer value) {
            addCriterion("route_status <", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusLessThanOrEqualTo(Integer value) {
            addCriterion("route_status <=", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusIn(List<Integer> values) {
            addCriterion("route_status in", values, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusNotIn(List<Integer> values) {
            addCriterion("route_status not in", values, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusBetween(Integer value1, Integer value2) {
            addCriterion("route_status between", value1, value2, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("route_status not between", value1, value2, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeIsNull() {
            addCriterion("recruit_time is null");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeIsNotNull() {
            addCriterion("recruit_time is not null");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeEqualTo(Date value) {
            addCriterion("recruit_time =", value, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeNotEqualTo(Date value) {
            addCriterion("recruit_time <>", value, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeGreaterThan(Date value) {
            addCriterion("recruit_time >", value, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("recruit_time >=", value, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeLessThan(Date value) {
            addCriterion("recruit_time <", value, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeLessThanOrEqualTo(Date value) {
            addCriterion("recruit_time <=", value, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeIn(List<Date> values) {
            addCriterion("recruit_time in", values, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeNotIn(List<Date> values) {
            addCriterion("recruit_time not in", values, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeBetween(Date value1, Date value2) {
            addCriterion("recruit_time between", value1, value2, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRecruitTimeNotBetween(Date value1, Date value2) {
            addCriterion("recruit_time not between", value1, value2, "recruitTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeIsNull() {
            addCriterion("run_time is null");
            return (Criteria) this;
        }

        public Criteria andRunTimeIsNotNull() {
            addCriterion("run_time is not null");
            return (Criteria) this;
        }

        public Criteria andRunTimeEqualTo(String value) {
            addCriterion("run_time =", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotEqualTo(String value) {
            addCriterion("run_time <>", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeGreaterThan(String value) {
            addCriterion("run_time >", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeGreaterThanOrEqualTo(String value) {
            addCriterion("run_time >=", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeLessThan(String value) {
            addCriterion("run_time <", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeLessThanOrEqualTo(String value) {
            addCriterion("run_time <=", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeLike(String value) {
            addCriterion("run_time like", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotLike(String value) {
            addCriterion("run_time not like", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeIn(List<String> values) {
            addCriterion("run_time in", values, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotIn(List<String> values) {
            addCriterion("run_time not in", values, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeBetween(String value1, String value2) {
            addCriterion("run_time between", value1, value2, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotBetween(String value1, String value2) {
            addCriterion("run_time not between", value1, value2, "runTime");
            return (Criteria) this;
        }

        public Criteria andStartSiteIsNull() {
            addCriterion("start_site is null");
            return (Criteria) this;
        }

        public Criteria andStartSiteIsNotNull() {
            addCriterion("start_site is not null");
            return (Criteria) this;
        }

        public Criteria andStartSiteEqualTo(String value) {
            addCriterion("start_site =", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteNotEqualTo(String value) {
            addCriterion("start_site <>", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteGreaterThan(String value) {
            addCriterion("start_site >", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteGreaterThanOrEqualTo(String value) {
            addCriterion("start_site >=", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteLessThan(String value) {
            addCriterion("start_site <", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteLessThanOrEqualTo(String value) {
            addCriterion("start_site <=", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteLike(String value) {
            addCriterion("start_site like", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteNotLike(String value) {
            addCriterion("start_site not like", value, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteIn(List<String> values) {
            addCriterion("start_site in", values, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteNotIn(List<String> values) {
            addCriterion("start_site not in", values, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteBetween(String value1, String value2) {
            addCriterion("start_site between", value1, value2, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartSiteNotBetween(String value1, String value2) {
            addCriterion("start_site not between", value1, value2, "startSite");
            return (Criteria) this;
        }

        public Criteria andStartCoordIsNull() {
            addCriterion("start_coord is null");
            return (Criteria) this;
        }

        public Criteria andStartCoordIsNotNull() {
            addCriterion("start_coord is not null");
            return (Criteria) this;
        }

        public Criteria andStartCoordEqualTo(String value) {
            addCriterion("start_coord =", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordNotEqualTo(String value) {
            addCriterion("start_coord <>", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordGreaterThan(String value) {
            addCriterion("start_coord >", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordGreaterThanOrEqualTo(String value) {
            addCriterion("start_coord >=", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordLessThan(String value) {
            addCriterion("start_coord <", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordLessThanOrEqualTo(String value) {
            addCriterion("start_coord <=", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordLike(String value) {
            addCriterion("start_coord like", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordNotLike(String value) {
            addCriterion("start_coord not like", value, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordIn(List<String> values) {
            addCriterion("start_coord in", values, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordNotIn(List<String> values) {
            addCriterion("start_coord not in", values, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordBetween(String value1, String value2) {
            addCriterion("start_coord between", value1, value2, "startCoord");
            return (Criteria) this;
        }

        public Criteria andStartCoordNotBetween(String value1, String value2) {
            addCriterion("start_coord not between", value1, value2, "startCoord");
            return (Criteria) this;
        }

        public Criteria andEndSiteIsNull() {
            addCriterion("end_site is null");
            return (Criteria) this;
        }

        public Criteria andEndSiteIsNotNull() {
            addCriterion("end_site is not null");
            return (Criteria) this;
        }

        public Criteria andEndSiteEqualTo(String value) {
            addCriterion("end_site =", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteNotEqualTo(String value) {
            addCriterion("end_site <>", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteGreaterThan(String value) {
            addCriterion("end_site >", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteGreaterThanOrEqualTo(String value) {
            addCriterion("end_site >=", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteLessThan(String value) {
            addCriterion("end_site <", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteLessThanOrEqualTo(String value) {
            addCriterion("end_site <=", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteLike(String value) {
            addCriterion("end_site like", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteNotLike(String value) {
            addCriterion("end_site not like", value, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteIn(List<String> values) {
            addCriterion("end_site in", values, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteNotIn(List<String> values) {
            addCriterion("end_site not in", values, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteBetween(String value1, String value2) {
            addCriterion("end_site between", value1, value2, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndSiteNotBetween(String value1, String value2) {
            addCriterion("end_site not between", value1, value2, "endSite");
            return (Criteria) this;
        }

        public Criteria andEndCoordIsNull() {
            addCriterion("end_coord is null");
            return (Criteria) this;
        }

        public Criteria andEndCoordIsNotNull() {
            addCriterion("end_coord is not null");
            return (Criteria) this;
        }

        public Criteria andEndCoordEqualTo(String value) {
            addCriterion("end_coord =", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordNotEqualTo(String value) {
            addCriterion("end_coord <>", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordGreaterThan(String value) {
            addCriterion("end_coord >", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordGreaterThanOrEqualTo(String value) {
            addCriterion("end_coord >=", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordLessThan(String value) {
            addCriterion("end_coord <", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordLessThanOrEqualTo(String value) {
            addCriterion("end_coord <=", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordLike(String value) {
            addCriterion("end_coord like", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordNotLike(String value) {
            addCriterion("end_coord not like", value, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordIn(List<String> values) {
            addCriterion("end_coord in", values, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordNotIn(List<String> values) {
            addCriterion("end_coord not in", values, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordBetween(String value1, String value2) {
            addCriterion("end_coord between", value1, value2, "endCoord");
            return (Criteria) this;
        }

        public Criteria andEndCoordNotBetween(String value1, String value2) {
            addCriterion("end_coord not between", value1, value2, "endCoord");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(String value) {
            addCriterion("station_id =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(String value) {
            addCriterion("station_id <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(String value) {
            addCriterion("station_id >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(String value) {
            addCriterion("station_id >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(String value) {
            addCriterion("station_id <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(String value) {
            addCriterion("station_id <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLike(String value) {
            addCriterion("station_id like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotLike(String value) {
            addCriterion("station_id not like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<String> values) {
            addCriterion("station_id in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<String> values) {
            addCriterion("station_id not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(String value1, String value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(String value1, String value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Float value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Float value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Float value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Float value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Float value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Float> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Float> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Float value1, Float value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Float value1, Float value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andRecruitNumIsNull() {
            addCriterion("recruit_num is null");
            return (Criteria) this;
        }

        public Criteria andRecruitNumIsNotNull() {
            addCriterion("recruit_num is not null");
            return (Criteria) this;
        }

        public Criteria andRecruitNumEqualTo(Integer value) {
            addCriterion("recruit_num =", value, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumNotEqualTo(Integer value) {
            addCriterion("recruit_num <>", value, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumGreaterThan(Integer value) {
            addCriterion("recruit_num >", value, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("recruit_num >=", value, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumLessThan(Integer value) {
            addCriterion("recruit_num <", value, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumLessThanOrEqualTo(Integer value) {
            addCriterion("recruit_num <=", value, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumIn(List<Integer> values) {
            addCriterion("recruit_num in", values, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumNotIn(List<Integer> values) {
            addCriterion("recruit_num not in", values, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumBetween(Integer value1, Integer value2) {
            addCriterion("recruit_num between", value1, value2, "recruitNum");
            return (Criteria) this;
        }

        public Criteria andRecruitNumNotBetween(Integer value1, Integer value2) {
            addCriterion("recruit_num not between", value1, value2, "recruitNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table route
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table route
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}