package java.com.wxbus.daomain;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbggenerated
     */
    private String adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_password
     *
     * @mbggenerated
     */
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_owner
     *
     * @mbggenerated
     */
    private String adminOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_power
     *
     * @mbggenerated
     */
    private Integer adminPower;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbggenerated
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param adminId the value for admin.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_password
     *
     * @return the value of admin.admin_password
     *
     * @mbggenerated
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_password
     *
     * @param adminPassword the value for admin.admin_password
     *
     * @mbggenerated
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_owner
     *
     * @return the value of admin.admin_owner
     *
     * @mbggenerated
     */
    public String getAdminOwner() {
        return adminOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_owner
     *
     * @param adminOwner the value for admin.admin_owner
     *
     * @mbggenerated
     */
    public void setAdminOwner(String adminOwner) {
        this.adminOwner = adminOwner == null ? null : adminOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_power
     *
     * @return the value of admin.admin_power
     *
     * @mbggenerated
     */
    public Integer getAdminPower() {
        return adminPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_power
     *
     * @param adminPower the value for admin.admin_power
     *
     * @mbggenerated
     */
    public void setAdminPower(Integer adminPower) {
        this.adminPower = adminPower;
    }
}