package java.com.wxbus.daomain;

import java.util.Date;

public class Route {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_id
     *
     * @mbggenerated
     */
    private Integer routeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.creat_user
     *
     * @mbggenerated
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_status
     *
     * @mbggenerated
     */
    private Integer routeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.recruit_time
     *
     * @mbggenerated
     */
    private Integer recruitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.run_time
     *
     * @mbggenerated
     */
    private String runTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.start_site
     *
     * @mbggenerated
     */
    private String startSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.start_coord
     *
     * @mbggenerated
     */
    private String startCoord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.end_site
     *
     * @mbggenerated
     */
    private String endSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.end_coord
     *
     * @mbggenerated
     */
    private String endCoord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.station_id
     *
     * @mbggenerated
     */
    private String stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.recruit_num
     *
     * @mbggenerated
     */
    private Integer recruitNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_id
     *
     * @return the value of route.route_id
     *
     * @mbggenerated
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_id
     *
     * @param routeId the value for route.route_id
     *
     * @mbggenerated
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.creat_user
     *
     * @return the value of route.creat_user
     *
     * @mbggenerated
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.creat_user
     *
     * @param creatUser the value for route.creat_user
     *
     * @mbggenerated
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser == null ? null : creatUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.creat_time
     *
     * @return the value of route.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.creat_time
     *
     * @param creatTime the value for route.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_status
     *
     * @return the value of route.route_status
     *
     * @mbggenerated
     */
    public Integer getRouteStatus() {
        return routeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_status
     *
     * @param routeStatus the value for route.route_status
     *
     * @mbggenerated
     */
    public void setRouteStatus(Integer routeStatus) {
        this.routeStatus = routeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.recruit_time
     *
     * @return the value of route.recruit_time
     *
     * @mbggenerated
     */
    public Integer getRecruitTime() {
        return recruitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.recruit_time
     *
     * @param recruitTime the value for route.recruit_time
     *
     * @mbggenerated
     */
    public void setRecruitTime(Integer recruitTime) {
        this.recruitTime = recruitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.run_time
     *
     * @return the value of route.run_time
     *
     * @mbggenerated
     */
    public String getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.run_time
     *
     * @param runTime the value for route.run_time
     *
     * @mbggenerated
     */
    public void setRunTime(String runTime) {
        this.runTime = runTime == null ? null : runTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.start_site
     *
     * @return the value of route.start_site
     *
     * @mbggenerated
     */
    public String getStartSite() {
        return startSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.start_site
     *
     * @param startSite the value for route.start_site
     *
     * @mbggenerated
     */
    public void setStartSite(String startSite) {
        this.startSite = startSite == null ? null : startSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.start_coord
     *
     * @return the value of route.start_coord
     *
     * @mbggenerated
     */
    public String getStartCoord() {
        return startCoord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.start_coord
     *
     * @param startCoord the value for route.start_coord
     *
     * @mbggenerated
     */
    public void setStartCoord(String startCoord) {
        this.startCoord = startCoord == null ? null : startCoord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.end_site
     *
     * @return the value of route.end_site
     *
     * @mbggenerated
     */
    public String getEndSite() {
        return endSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.end_site
     *
     * @param endSite the value for route.end_site
     *
     * @mbggenerated
     */
    public void setEndSite(String endSite) {
        this.endSite = endSite == null ? null : endSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.end_coord
     *
     * @return the value of route.end_coord
     *
     * @mbggenerated
     */
    public String getEndCoord() {
        return endCoord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.end_coord
     *
     * @param endCoord the value for route.end_coord
     *
     * @mbggenerated
     */
    public void setEndCoord(String endCoord) {
        this.endCoord = endCoord == null ? null : endCoord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.station_id
     *
     * @return the value of route.station_id
     *
     * @mbggenerated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.station_id
     *
     * @param stationId the value for route.station_id
     *
     * @mbggenerated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.start_time
     *
     * @return the value of route.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.start_time
     *
     * @param startTime the value for route.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.end_time
     *
     * @return the value of route.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.end_time
     *
     * @param endTime the value for route.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.price
     *
     * @return the value of route.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.price
     *
     * @param price the value for route.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.recruit_num
     *
     * @return the value of route.recruit_num
     *
     * @mbggenerated
     */
    public Integer getRecruitNum() {
        return recruitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.recruit_num
     *
     * @param recruitNum the value for route.recruit_num
     *
     * @mbggenerated
     */
    public void setRecruitNum(Integer recruitNum) {
        this.recruitNum = recruitNum;
    }
}