package com.wxbus.daomain;

import java.util.Date;

public class Bus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.bus_num
     *
     * @mbggenerated
     */
    private Integer busNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.bus_id
     *
     * @mbggenerated
     */
    private String busId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.bus_type
     *
     * @mbggenerated
     */
    private String busType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.bus_owner
     *
     * @mbggenerated
     */
    private String busOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.characters
     *
     * @mbggenerated
     */
    private String characters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.VIN
     *
     * @mbggenerated
     */
    private String vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.engine_num
     *
     * @mbggenerated
     */
    private String engineNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.registration_date
     *
     * @mbggenerated
     */
    private Date registrationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.oppen_date
     *
     * @mbggenerated
     */
    private Date oppenDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.seating
     *
     * @mbggenerated
     */
    private Integer seating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.bus_status
     *
     * @mbggenerated
     */
    private Integer busStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus.bus_mark
     *
     * @mbggenerated
     */
    private Integer busMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.bus_num
     *
     * @return the value of bus.bus_num
     *
     * @mbggenerated
     */
    public Integer getBusNum() {
        return busNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.bus_num
     *
     * @param busNum the value for bus.bus_num
     *
     * @mbggenerated
     */
    public void setBusNum(Integer busNum) {
        this.busNum = busNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.bus_id
     *
     * @return the value of bus.bus_id
     *
     * @mbggenerated
     */
    public String getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.bus_id
     *
     * @param busId the value for bus.bus_id
     *
     * @mbggenerated
     */
    public void setBusId(String busId) {
        this.busId = busId == null ? null : busId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.bus_type
     *
     * @return the value of bus.bus_type
     *
     * @mbggenerated
     */
    public String getBusType() {
        return busType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.bus_type
     *
     * @param busType the value for bus.bus_type
     *
     * @mbggenerated
     */
    public void setBusType(String busType) {
        this.busType = busType == null ? null : busType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.bus_owner
     *
     * @return the value of bus.bus_owner
     *
     * @mbggenerated
     */
    public String getBusOwner() {
        return busOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.bus_owner
     *
     * @param busOwner the value for bus.bus_owner
     *
     * @mbggenerated
     */
    public void setBusOwner(String busOwner) {
        this.busOwner = busOwner == null ? null : busOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.characters
     *
     * @return the value of bus.characters
     *
     * @mbggenerated
     */
    public String getCharacters() {
        return characters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.characters
     *
     * @param characters the value for bus.characters
     *
     * @mbggenerated
     */
    public void setCharacters(String characters) {
        this.characters = characters == null ? null : characters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.model
     *
     * @return the value of bus.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.model
     *
     * @param model the value for bus.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.VIN
     *
     * @return the value of bus.VIN
     *
     * @mbggenerated
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.VIN
     *
     * @param vin the value for bus.VIN
     *
     * @mbggenerated
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.engine_num
     *
     * @return the value of bus.engine_num
     *
     * @mbggenerated
     */
    public String getEngineNum() {
        return engineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.engine_num
     *
     * @param engineNum the value for bus.engine_num
     *
     * @mbggenerated
     */
    public void setEngineNum(String engineNum) {
        this.engineNum = engineNum == null ? null : engineNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.registration_date
     *
     * @return the value of bus.registration_date
     *
     * @mbggenerated
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.registration_date
     *
     * @param registrationDate the value for bus.registration_date
     *
     * @mbggenerated
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.oppen_date
     *
     * @return the value of bus.oppen_date
     *
     * @mbggenerated
     */
    public Date getOppenDate() {
        return oppenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.oppen_date
     *
     * @param oppenDate the value for bus.oppen_date
     *
     * @mbggenerated
     */
    public void setOppenDate(Date oppenDate) {
        this.oppenDate = oppenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.seating
     *
     * @return the value of bus.seating
     *
     * @mbggenerated
     */
    public Integer getSeating() {
        return seating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.seating
     *
     * @param seating the value for bus.seating
     *
     * @mbggenerated
     */
    public void setSeating(Integer seating) {
        this.seating = seating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.bus_status
     *
     * @return the value of bus.bus_status
     *
     * @mbggenerated
     */
    public Integer getBusStatus() {
        return busStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.bus_status
     *
     * @param busStatus the value for bus.bus_status
     *
     * @mbggenerated
     */
    public void setBusStatus(Integer busStatus) {
        this.busStatus = busStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus.bus_mark
     *
     * @return the value of bus.bus_mark
     *
     * @mbggenerated
     */
    public Integer getBusMark() {
        return busMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus.bus_mark
     *
     * @param busMark the value for bus.bus_mark
     *
     * @mbggenerated
     */
    public void setBusMark(Integer busMark) {
        this.busMark = busMark;
    }
}