package com.wxbus.daomain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DriverBusRouteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public DriverBusRouteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDBRIdIsNull() {
            addCriterion("d_b_r_id is null");
            return (Criteria) this;
        }

        public Criteria andDBRIdIsNotNull() {
            addCriterion("d_b_r_id is not null");
            return (Criteria) this;
        }

        public Criteria andDBRIdEqualTo(Integer value) {
            addCriterion("d_b_r_id =", value, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdNotEqualTo(Integer value) {
            addCriterion("d_b_r_id <>", value, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdGreaterThan(Integer value) {
            addCriterion("d_b_r_id >", value, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("d_b_r_id >=", value, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdLessThan(Integer value) {
            addCriterion("d_b_r_id <", value, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdLessThanOrEqualTo(Integer value) {
            addCriterion("d_b_r_id <=", value, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdIn(List<Integer> values) {
            addCriterion("d_b_r_id in", values, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdNotIn(List<Integer> values) {
            addCriterion("d_b_r_id not in", values, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdBetween(Integer value1, Integer value2) {
            addCriterion("d_b_r_id between", value1, value2, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDBRIdNotBetween(Integer value1, Integer value2) {
            addCriterion("d_b_r_id not between", value1, value2, "dBRId");
            return (Criteria) this;
        }

        public Criteria andDriverIdIsNull() {
            addCriterion("driver_id is null");
            return (Criteria) this;
        }

        public Criteria andDriverIdIsNotNull() {
            addCriterion("driver_id is not null");
            return (Criteria) this;
        }

        public Criteria andDriverIdEqualTo(String value) {
            addCriterion("driver_id =", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotEqualTo(String value) {
            addCriterion("driver_id <>", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdGreaterThan(String value) {
            addCriterion("driver_id >", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdGreaterThanOrEqualTo(String value) {
            addCriterion("driver_id >=", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdLessThan(String value) {
            addCriterion("driver_id <", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdLessThanOrEqualTo(String value) {
            addCriterion("driver_id <=", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdLike(String value) {
            addCriterion("driver_id like", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotLike(String value) {
            addCriterion("driver_id not like", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdIn(List<String> values) {
            addCriterion("driver_id in", values, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotIn(List<String> values) {
            addCriterion("driver_id not in", values, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdBetween(String value1, String value2) {
            addCriterion("driver_id between", value1, value2, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotBetween(String value1, String value2) {
            addCriterion("driver_id not between", value1, value2, "driverId");
            return (Criteria) this;
        }

        public Criteria andBusIdIsNull() {
            addCriterion("bus_id is null");
            return (Criteria) this;
        }

        public Criteria andBusIdIsNotNull() {
            addCriterion("bus_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusIdEqualTo(String value) {
            addCriterion("bus_id =", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotEqualTo(String value) {
            addCriterion("bus_id <>", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdGreaterThan(String value) {
            addCriterion("bus_id >", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdGreaterThanOrEqualTo(String value) {
            addCriterion("bus_id >=", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdLessThan(String value) {
            addCriterion("bus_id <", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdLessThanOrEqualTo(String value) {
            addCriterion("bus_id <=", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdLike(String value) {
            addCriterion("bus_id like", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotLike(String value) {
            addCriterion("bus_id not like", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdIn(List<String> values) {
            addCriterion("bus_id in", values, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotIn(List<String> values) {
            addCriterion("bus_id not in", values, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdBetween(String value1, String value2) {
            addCriterion("bus_id between", value1, value2, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotBetween(String value1, String value2) {
            addCriterion("bus_id not between", value1, value2, "busId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNull() {
            addCriterion("route_id is null");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNotNull() {
            addCriterion("route_id is not null");
            return (Criteria) this;
        }

        public Criteria andRouteIdEqualTo(Integer value) {
            addCriterion("route_id =", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotEqualTo(Integer value) {
            addCriterion("route_id <>", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThan(Integer value) {
            addCriterion("route_id >", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_id >=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThan(Integer value) {
            addCriterion("route_id <", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThanOrEqualTo(Integer value) {
            addCriterion("route_id <=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIn(List<Integer> values) {
            addCriterion("route_id in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotIn(List<Integer> values) {
            addCriterion("route_id not in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdBetween(Integer value1, Integer value2) {
            addCriterion("route_id between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("route_id not between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andDirverTimeIsNull() {
            addCriterion("dirver_time is null");
            return (Criteria) this;
        }

        public Criteria andDirverTimeIsNotNull() {
            addCriterion("dirver_time is not null");
            return (Criteria) this;
        }

        public Criteria andDirverTimeEqualTo(Date value) {
            addCriterion("dirver_time =", value, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeNotEqualTo(Date value) {
            addCriterion("dirver_time <>", value, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeGreaterThan(Date value) {
            addCriterion("dirver_time >", value, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("dirver_time >=", value, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeLessThan(Date value) {
            addCriterion("dirver_time <", value, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeLessThanOrEqualTo(Date value) {
            addCriterion("dirver_time <=", value, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeIn(List<Date> values) {
            addCriterion("dirver_time in", values, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeNotIn(List<Date> values) {
            addCriterion("dirver_time not in", values, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeBetween(Date value1, Date value2) {
            addCriterion("dirver_time between", value1, value2, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andDirverTimeNotBetween(Date value1, Date value2) {
            addCriterion("dirver_time not between", value1, value2, "dirverTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeIsNull() {
            addCriterion("bus_time is null");
            return (Criteria) this;
        }

        public Criteria andBusTimeIsNotNull() {
            addCriterion("bus_time is not null");
            return (Criteria) this;
        }

        public Criteria andBusTimeEqualTo(Date value) {
            addCriterion("bus_time =", value, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeNotEqualTo(Date value) {
            addCriterion("bus_time <>", value, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeGreaterThan(Date value) {
            addCriterion("bus_time >", value, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("bus_time >=", value, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeLessThan(Date value) {
            addCriterion("bus_time <", value, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeLessThanOrEqualTo(Date value) {
            addCriterion("bus_time <=", value, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeIn(List<Date> values) {
            addCriterion("bus_time in", values, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeNotIn(List<Date> values) {
            addCriterion("bus_time not in", values, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeBetween(Date value1, Date value2) {
            addCriterion("bus_time between", value1, value2, "busTime");
            return (Criteria) this;
        }

        public Criteria andBusTimeNotBetween(Date value1, Date value2) {
            addCriterion("bus_time not between", value1, value2, "busTime");
            return (Criteria) this;
        }

        public Criteria andRouteStatusIsNull() {
            addCriterion("route_status is null");
            return (Criteria) this;
        }

        public Criteria andRouteStatusIsNotNull() {
            addCriterion("route_status is not null");
            return (Criteria) this;
        }

        public Criteria andRouteStatusEqualTo(Integer value) {
            addCriterion("route_status =", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusNotEqualTo(Integer value) {
            addCriterion("route_status <>", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusGreaterThan(Integer value) {
            addCriterion("route_status >", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_status >=", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusLessThan(Integer value) {
            addCriterion("route_status <", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusLessThanOrEqualTo(Integer value) {
            addCriterion("route_status <=", value, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusIn(List<Integer> values) {
            addCriterion("route_status in", values, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusNotIn(List<Integer> values) {
            addCriterion("route_status not in", values, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusBetween(Integer value1, Integer value2) {
            addCriterion("route_status between", value1, value2, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andRouteStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("route_status not between", value1, value2, "routeStatus");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeIsNull() {
            addCriterion("driver_out_time is null");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeIsNotNull() {
            addCriterion("driver_out_time is not null");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeEqualTo(Date value) {
            addCriterion("driver_out_time =", value, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeNotEqualTo(Date value) {
            addCriterion("driver_out_time <>", value, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeGreaterThan(Date value) {
            addCriterion("driver_out_time >", value, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("driver_out_time >=", value, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeLessThan(Date value) {
            addCriterion("driver_out_time <", value, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeLessThanOrEqualTo(Date value) {
            addCriterion("driver_out_time <=", value, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeIn(List<Date> values) {
            addCriterion("driver_out_time in", values, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeNotIn(List<Date> values) {
            addCriterion("driver_out_time not in", values, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeBetween(Date value1, Date value2) {
            addCriterion("driver_out_time between", value1, value2, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverOutTimeNotBetween(Date value1, Date value2) {
            addCriterion("driver_out_time not between", value1, value2, "driverOutTime");
            return (Criteria) this;
        }

        public Criteria andDriverStatusIsNull() {
            addCriterion("driver_status is null");
            return (Criteria) this;
        }

        public Criteria andDriverStatusIsNotNull() {
            addCriterion("driver_status is not null");
            return (Criteria) this;
        }

        public Criteria andDriverStatusEqualTo(Integer value) {
            addCriterion("driver_status =", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusNotEqualTo(Integer value) {
            addCriterion("driver_status <>", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusGreaterThan(Integer value) {
            addCriterion("driver_status >", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_status >=", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusLessThan(Integer value) {
            addCriterion("driver_status <", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusLessThanOrEqualTo(Integer value) {
            addCriterion("driver_status <=", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusIn(List<Integer> values) {
            addCriterion("driver_status in", values, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusNotIn(List<Integer> values) {
            addCriterion("driver_status not in", values, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusBetween(Integer value1, Integer value2) {
            addCriterion("driver_status between", value1, value2, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_status not between", value1, value2, "driverStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver_bus_route
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}