package com.wxbus.daomain;

public class DriverKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_num
     *
     * @mbggenerated
     */
    private Integer driverNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_citizenship
     *
     * @mbggenerated
     */
    private String driverCitizenship;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_num
     *
     * @return the value of driver.driver_num
     *
     * @mbggenerated
     */
    public Integer getDriverNum() {
        return driverNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_num
     *
     * @param driverNum the value for driver.driver_num
     *
     * @mbggenerated
     */
    public void setDriverNum(Integer driverNum) {
        this.driverNum = driverNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_citizenship
     *
     * @return the value of driver.driver_citizenship
     *
     * @mbggenerated
     */
    public String getDriverCitizenship() {
        return driverCitizenship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_citizenship
     *
     * @param driverCitizenship the value for driver.driver_citizenship
     *
     * @mbggenerated
     */
    public void setDriverCitizenship(String driverCitizenship) {
        this.driverCitizenship = driverCitizenship == null ? null : driverCitizenship.trim();
    }
}