package com.wxbus.daomain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DriverExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public DriverExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andDriverNumIsNull() {
            addCriterion("driver_num is null");
            return (Criteria) this;
        }

        public Criteria andDriverNumIsNotNull() {
            addCriterion("driver_num is not null");
            return (Criteria) this;
        }

        public Criteria andDriverNumEqualTo(Integer value) {
            addCriterion("driver_num =", value, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumNotEqualTo(Integer value) {
            addCriterion("driver_num <>", value, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumGreaterThan(Integer value) {
            addCriterion("driver_num >", value, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_num >=", value, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumLessThan(Integer value) {
            addCriterion("driver_num <", value, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumLessThanOrEqualTo(Integer value) {
            addCriterion("driver_num <=", value, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumIn(List<Integer> values) {
            addCriterion("driver_num in", values, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumNotIn(List<Integer> values) {
            addCriterion("driver_num not in", values, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumBetween(Integer value1, Integer value2) {
            addCriterion("driver_num between", value1, value2, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverNumNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_num not between", value1, value2, "driverNum");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipIsNull() {
            addCriterion("driver_citizenship is null");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipIsNotNull() {
            addCriterion("driver_citizenship is not null");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipEqualTo(String value) {
            addCriterion("driver_citizenship =", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipNotEqualTo(String value) {
            addCriterion("driver_citizenship <>", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipGreaterThan(String value) {
            addCriterion("driver_citizenship >", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipGreaterThanOrEqualTo(String value) {
            addCriterion("driver_citizenship >=", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipLessThan(String value) {
            addCriterion("driver_citizenship <", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipLessThanOrEqualTo(String value) {
            addCriterion("driver_citizenship <=", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipLike(String value) {
            addCriterion("driver_citizenship like", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipNotLike(String value) {
            addCriterion("driver_citizenship not like", value, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipIn(List<String> values) {
            addCriterion("driver_citizenship in", values, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipNotIn(List<String> values) {
            addCriterion("driver_citizenship not in", values, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipBetween(String value1, String value2) {
            addCriterion("driver_citizenship between", value1, value2, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverCitizenshipNotBetween(String value1, String value2) {
            addCriterion("driver_citizenship not between", value1, value2, "driverCitizenship");
            return (Criteria) this;
        }

        public Criteria andDriverIdIsNull() {
            addCriterion("driver_id is null");
            return (Criteria) this;
        }

        public Criteria andDriverIdIsNotNull() {
            addCriterion("driver_id is not null");
            return (Criteria) this;
        }

        public Criteria andDriverIdEqualTo(String value) {
            addCriterion("driver_id =", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotEqualTo(String value) {
            addCriterion("driver_id <>", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdGreaterThan(String value) {
            addCriterion("driver_id >", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdGreaterThanOrEqualTo(String value) {
            addCriterion("driver_id >=", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdLessThan(String value) {
            addCriterion("driver_id <", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdLessThanOrEqualTo(String value) {
            addCriterion("driver_id <=", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdLike(String value) {
            addCriterion("driver_id like", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotLike(String value) {
            addCriterion("driver_id not like", value, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdIn(List<String> values) {
            addCriterion("driver_id in", values, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotIn(List<String> values) {
            addCriterion("driver_id not in", values, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdBetween(String value1, String value2) {
            addCriterion("driver_id between", value1, value2, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotBetween(String value1, String value2) {
            addCriterion("driver_id not between", value1, value2, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverNameIsNull() {
            addCriterion("driver_name is null");
            return (Criteria) this;
        }

        public Criteria andDriverNameIsNotNull() {
            addCriterion("driver_name is not null");
            return (Criteria) this;
        }

        public Criteria andDriverNameEqualTo(String value) {
            addCriterion("driver_name =", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotEqualTo(String value) {
            addCriterion("driver_name <>", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameGreaterThan(String value) {
            addCriterion("driver_name >", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameGreaterThanOrEqualTo(String value) {
            addCriterion("driver_name >=", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameLessThan(String value) {
            addCriterion("driver_name <", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameLessThanOrEqualTo(String value) {
            addCriterion("driver_name <=", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameLike(String value) {
            addCriterion("driver_name like", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotLike(String value) {
            addCriterion("driver_name not like", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameIn(List<String> values) {
            addCriterion("driver_name in", values, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotIn(List<String> values) {
            addCriterion("driver_name not in", values, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameBetween(String value1, String value2) {
            addCriterion("driver_name between", value1, value2, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotBetween(String value1, String value2) {
            addCriterion("driver_name not between", value1, value2, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverGenderIsNull() {
            addCriterion("driver_gender is null");
            return (Criteria) this;
        }

        public Criteria andDriverGenderIsNotNull() {
            addCriterion("driver_gender is not null");
            return (Criteria) this;
        }

        public Criteria andDriverGenderEqualTo(String value) {
            addCriterion("driver_gender =", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderNotEqualTo(String value) {
            addCriterion("driver_gender <>", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderGreaterThan(String value) {
            addCriterion("driver_gender >", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderGreaterThanOrEqualTo(String value) {
            addCriterion("driver_gender >=", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderLessThan(String value) {
            addCriterion("driver_gender <", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderLessThanOrEqualTo(String value) {
            addCriterion("driver_gender <=", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderLike(String value) {
            addCriterion("driver_gender like", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderNotLike(String value) {
            addCriterion("driver_gender not like", value, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderIn(List<String> values) {
            addCriterion("driver_gender in", values, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderNotIn(List<String> values) {
            addCriterion("driver_gender not in", values, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderBetween(String value1, String value2) {
            addCriterion("driver_gender between", value1, value2, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverGenderNotBetween(String value1, String value2) {
            addCriterion("driver_gender not between", value1, value2, "driverGender");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordIsNull() {
            addCriterion("driver_password is null");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordIsNotNull() {
            addCriterion("driver_password is not null");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordEqualTo(String value) {
            addCriterion("driver_password =", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordNotEqualTo(String value) {
            addCriterion("driver_password <>", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordGreaterThan(String value) {
            addCriterion("driver_password >", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("driver_password >=", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordLessThan(String value) {
            addCriterion("driver_password <", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordLessThanOrEqualTo(String value) {
            addCriterion("driver_password <=", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordLike(String value) {
            addCriterion("driver_password like", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordNotLike(String value) {
            addCriterion("driver_password not like", value, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordIn(List<String> values) {
            addCriterion("driver_password in", values, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordNotIn(List<String> values) {
            addCriterion("driver_password not in", values, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordBetween(String value1, String value2) {
            addCriterion("driver_password between", value1, value2, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverPasswordNotBetween(String value1, String value2) {
            addCriterion("driver_password not between", value1, value2, "driverPassword");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterIsNull() {
            addCriterion("driver_avater is null");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterIsNotNull() {
            addCriterion("driver_avater is not null");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterEqualTo(String value) {
            addCriterion("driver_avater =", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterNotEqualTo(String value) {
            addCriterion("driver_avater <>", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterGreaterThan(String value) {
            addCriterion("driver_avater >", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterGreaterThanOrEqualTo(String value) {
            addCriterion("driver_avater >=", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterLessThan(String value) {
            addCriterion("driver_avater <", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterLessThanOrEqualTo(String value) {
            addCriterion("driver_avater <=", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterLike(String value) {
            addCriterion("driver_avater like", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterNotLike(String value) {
            addCriterion("driver_avater not like", value, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterIn(List<String> values) {
            addCriterion("driver_avater in", values, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterNotIn(List<String> values) {
            addCriterion("driver_avater not in", values, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterBetween(String value1, String value2) {
            addCriterion("driver_avater between", value1, value2, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverAvaterNotBetween(String value1, String value2) {
            addCriterion("driver_avater not between", value1, value2, "driverAvater");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityIsNull() {
            addCriterion("driver_nationality is null");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityIsNotNull() {
            addCriterion("driver_nationality is not null");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityEqualTo(String value) {
            addCriterion("driver_nationality =", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityNotEqualTo(String value) {
            addCriterion("driver_nationality <>", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityGreaterThan(String value) {
            addCriterion("driver_nationality >", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("driver_nationality >=", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityLessThan(String value) {
            addCriterion("driver_nationality <", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityLessThanOrEqualTo(String value) {
            addCriterion("driver_nationality <=", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityLike(String value) {
            addCriterion("driver_nationality like", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityNotLike(String value) {
            addCriterion("driver_nationality not like", value, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityIn(List<String> values) {
            addCriterion("driver_nationality in", values, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityNotIn(List<String> values) {
            addCriterion("driver_nationality not in", values, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityBetween(String value1, String value2) {
            addCriterion("driver_nationality between", value1, value2, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverNationalityNotBetween(String value1, String value2) {
            addCriterion("driver_nationality not between", value1, value2, "driverNationality");
            return (Criteria) this;
        }

        public Criteria andDriverAddressIsNull() {
            addCriterion("driver_address is null");
            return (Criteria) this;
        }

        public Criteria andDriverAddressIsNotNull() {
            addCriterion("driver_address is not null");
            return (Criteria) this;
        }

        public Criteria andDriverAddressEqualTo(String value) {
            addCriterion("driver_address =", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressNotEqualTo(String value) {
            addCriterion("driver_address <>", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressGreaterThan(String value) {
            addCriterion("driver_address >", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressGreaterThanOrEqualTo(String value) {
            addCriterion("driver_address >=", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressLessThan(String value) {
            addCriterion("driver_address <", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressLessThanOrEqualTo(String value) {
            addCriterion("driver_address <=", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressLike(String value) {
            addCriterion("driver_address like", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressNotLike(String value) {
            addCriterion("driver_address not like", value, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressIn(List<String> values) {
            addCriterion("driver_address in", values, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressNotIn(List<String> values) {
            addCriterion("driver_address not in", values, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressBetween(String value1, String value2) {
            addCriterion("driver_address between", value1, value2, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andDriverAddressNotBetween(String value1, String value2) {
            addCriterion("driver_address not between", value1, value2, "driverAddress");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceIsNull() {
            addCriterion("first_getlicence is null");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceIsNotNull() {
            addCriterion("first_getlicence is not null");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceEqualTo(Date value) {
            addCriterionForJDBCDate("first_getlicence =", value, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceNotEqualTo(Date value) {
            addCriterionForJDBCDate("first_getlicence <>", value, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceGreaterThan(Date value) {
            addCriterionForJDBCDate("first_getlicence >", value, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("first_getlicence >=", value, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceLessThan(Date value) {
            addCriterionForJDBCDate("first_getlicence <", value, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("first_getlicence <=", value, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceIn(List<Date> values) {
            addCriterionForJDBCDate("first_getlicence in", values, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceNotIn(List<Date> values) {
            addCriterionForJDBCDate("first_getlicence not in", values, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("first_getlicence between", value1, value2, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andFirstGetlicenceNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("first_getlicence not between", value1, value2, "firstGetlicence");
            return (Criteria) this;
        }

        public Criteria andDriverMobileIsNull() {
            addCriterion("driver_mobile is null");
            return (Criteria) this;
        }

        public Criteria andDriverMobileIsNotNull() {
            addCriterion("driver_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andDriverMobileEqualTo(String value) {
            addCriterion("driver_mobile =", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileNotEqualTo(String value) {
            addCriterion("driver_mobile <>", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileGreaterThan(String value) {
            addCriterion("driver_mobile >", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileGreaterThanOrEqualTo(String value) {
            addCriterion("driver_mobile >=", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileLessThan(String value) {
            addCriterion("driver_mobile <", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileLessThanOrEqualTo(String value) {
            addCriterion("driver_mobile <=", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileLike(String value) {
            addCriterion("driver_mobile like", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileNotLike(String value) {
            addCriterion("driver_mobile not like", value, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileIn(List<String> values) {
            addCriterion("driver_mobile in", values, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileNotIn(List<String> values) {
            addCriterion("driver_mobile not in", values, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileBetween(String value1, String value2) {
            addCriterion("driver_mobile between", value1, value2, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andDriverMobileNotBetween(String value1, String value2) {
            addCriterion("driver_mobile not between", value1, value2, "driverMobile");
            return (Criteria) this;
        }

        public Criteria andRegisterIpIsNull() {
            addCriterion("register_ip is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIpIsNotNull() {
            addCriterion("register_ip is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIpEqualTo(String value) {
            addCriterion("register_ip =", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotEqualTo(String value) {
            addCriterion("register_ip <>", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpGreaterThan(String value) {
            addCriterion("register_ip >", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpGreaterThanOrEqualTo(String value) {
            addCriterion("register_ip >=", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpLessThan(String value) {
            addCriterion("register_ip <", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpLessThanOrEqualTo(String value) {
            addCriterion("register_ip <=", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpLike(String value) {
            addCriterion("register_ip like", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotLike(String value) {
            addCriterion("register_ip not like", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpIn(List<String> values) {
            addCriterion("register_ip in", values, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotIn(List<String> values) {
            addCriterion("register_ip not in", values, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpBetween(String value1, String value2) {
            addCriterion("register_ip between", value1, value2, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotBetween(String value1, String value2) {
            addCriterion("register_ip not between", value1, value2, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("register_time is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("register_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("register_time =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("register_time <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("register_time >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("register_time >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("register_time <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("register_time <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("register_time in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("register_time not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("register_time between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("register_time not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("last_login_time is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("last_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("last_login_time =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("last_login_time <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("last_login_time >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login_time >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("last_login_time <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_login_time <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("last_login_time in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("last_login_time not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("last_login_time between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNull() {
            addCriterion("last_login_ip is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNotNull() {
            addCriterion("last_login_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpEqualTo(String value) {
            addCriterion("last_login_ip =", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotEqualTo(String value) {
            addCriterion("last_login_ip <>", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThan(String value) {
            addCriterion("last_login_ip >", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("last_login_ip >=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThan(String value) {
            addCriterion("last_login_ip <", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThanOrEqualTo(String value) {
            addCriterion("last_login_ip <=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLike(String value) {
            addCriterion("last_login_ip like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotLike(String value) {
            addCriterion("last_login_ip not like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIn(List<String> values) {
            addCriterion("last_login_ip in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotIn(List<String> values) {
            addCriterion("last_login_ip not in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpBetween(String value1, String value2) {
            addCriterion("last_login_ip between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotBetween(String value1, String value2) {
            addCriterion("last_login_ip not between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeIsNull() {
            addCriterion("driving_type is null");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeIsNotNull() {
            addCriterion("driving_type is not null");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeEqualTo(String value) {
            addCriterion("driving_type =", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeNotEqualTo(String value) {
            addCriterion("driving_type <>", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeGreaterThan(String value) {
            addCriterion("driving_type >", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("driving_type >=", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeLessThan(String value) {
            addCriterion("driving_type <", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeLessThanOrEqualTo(String value) {
            addCriterion("driving_type <=", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeLike(String value) {
            addCriterion("driving_type like", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeNotLike(String value) {
            addCriterion("driving_type not like", value, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeIn(List<String> values) {
            addCriterion("driving_type in", values, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeNotIn(List<String> values) {
            addCriterion("driving_type not in", values, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeBetween(String value1, String value2) {
            addCriterion("driving_type between", value1, value2, "drivingType");
            return (Criteria) this;
        }

        public Criteria andDrivingTypeNotBetween(String value1, String value2) {
            addCriterion("driving_type not between", value1, value2, "drivingType");
            return (Criteria) this;
        }

        public Criteria andIntegralIsNull() {
            addCriterion("integral is null");
            return (Criteria) this;
        }

        public Criteria andIntegralIsNotNull() {
            addCriterion("integral is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralEqualTo(Integer value) {
            addCriterion("integral =", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotEqualTo(Integer value) {
            addCriterion("integral <>", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralGreaterThan(Integer value) {
            addCriterion("integral >", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("integral >=", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralLessThan(Integer value) {
            addCriterion("integral <", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("integral <=", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralIn(List<Integer> values) {
            addCriterion("integral in", values, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotIn(List<Integer> values) {
            addCriterion("integral not in", values, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralBetween(Integer value1, Integer value2) {
            addCriterion("integral between", value1, value2, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("integral not between", value1, value2, "integral");
            return (Criteria) this;
        }

        public Criteria andDriverMarkIsNull() {
            addCriterion("driver_mark is null");
            return (Criteria) this;
        }

        public Criteria andDriverMarkIsNotNull() {
            addCriterion("driver_mark is not null");
            return (Criteria) this;
        }

        public Criteria andDriverMarkEqualTo(Integer value) {
            addCriterion("driver_mark =", value, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkNotEqualTo(Integer value) {
            addCriterion("driver_mark <>", value, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkGreaterThan(Integer value) {
            addCriterion("driver_mark >", value, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_mark >=", value, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkLessThan(Integer value) {
            addCriterion("driver_mark <", value, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkLessThanOrEqualTo(Integer value) {
            addCriterion("driver_mark <=", value, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkIn(List<Integer> values) {
            addCriterion("driver_mark in", values, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkNotIn(List<Integer> values) {
            addCriterion("driver_mark not in", values, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkBetween(Integer value1, Integer value2) {
            addCriterion("driver_mark between", value1, value2, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverMarkNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_mark not between", value1, value2, "driverMark");
            return (Criteria) this;
        }

        public Criteria andDriverStatusIsNull() {
            addCriterion("driver_status is null");
            return (Criteria) this;
        }

        public Criteria andDriverStatusIsNotNull() {
            addCriterion("driver_status is not null");
            return (Criteria) this;
        }

        public Criteria andDriverStatusEqualTo(Integer value) {
            addCriterion("driver_status =", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusNotEqualTo(Integer value) {
            addCriterion("driver_status <>", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusGreaterThan(Integer value) {
            addCriterion("driver_status >", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_status >=", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusLessThan(Integer value) {
            addCriterion("driver_status <", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusLessThanOrEqualTo(Integer value) {
            addCriterion("driver_status <=", value, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusIn(List<Integer> values) {
            addCriterion("driver_status in", values, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusNotIn(List<Integer> values) {
            addCriterion("driver_status not in", values, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusBetween(Integer value1, Integer value2) {
            addCriterion("driver_status between", value1, value2, "driverStatus");
            return (Criteria) this;
        }

        public Criteria andDriverStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_status not between", value1, value2, "driverStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}