package com.wxbus.daomain;

public class Helper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper.help_Id
     *
     * @mbggenerated
     */
    private Integer helpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper.help_name
     *
     * @mbggenerated
     */
    private String helpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper.help_message
     *
     * @mbggenerated
     */
    private String helpMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column helper.help_Id
     *
     * @return the value of helper.help_Id
     *
     * @mbggenerated
     */
    public Integer getHelpId() {
        return helpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column helper.help_Id
     *
     * @param helpId the value for helper.help_Id
     *
     * @mbggenerated
     */
    public void setHelpId(Integer helpId) {
        this.helpId = helpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column helper.help_name
     *
     * @return the value of helper.help_name
     *
     * @mbggenerated
     */
    public String getHelpName() {
        return helpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column helper.help_name
     *
     * @param helpName the value for helper.help_name
     *
     * @mbggenerated
     */
    public void setHelpName(String helpName) {
        this.helpName = helpName == null ? null : helpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column helper.help_message
     *
     * @return the value of helper.help_message
     *
     * @mbggenerated
     */
    public String getHelpMessage() {
        return helpMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column helper.help_message
     *
     * @param helpMessage the value for helper.help_message
     *
     * @mbggenerated
     */
    public void setHelpMessage(String helpMessage) {
        this.helpMessage = helpMessage == null ? null : helpMessage.trim();
    }
}