package com.wxbus.daomain;

public class OverallConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overall_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overall_config.routeInquiryPeriod
     *
     * @mbggenerated
     */
    private Integer routeinquiryperiod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overall_config.id
     *
     * @return the value of overall_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overall_config.id
     *
     * @param id the value for overall_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overall_config.routeInquiryPeriod
     *
     * @return the value of overall_config.routeInquiryPeriod
     *
     * @mbggenerated
     */
    public Integer getRouteinquiryperiod() {
        return routeinquiryperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overall_config.routeInquiryPeriod
     *
     * @param routeinquiryperiod the value for overall_config.routeInquiryPeriod
     *
     * @mbggenerated
     */
    public void setRouteinquiryperiod(Integer routeinquiryperiod) {
        this.routeinquiryperiod = routeinquiryperiod;
    }
}