package com.wxbus.daomain;

import java.util.ArrayList;
import java.util.List;

public class StationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public StationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(Integer value) {
            addCriterion("station_id =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(Integer value) {
            addCriterion("station_id <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(Integer value) {
            addCriterion("station_id >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("station_id >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(Integer value) {
            addCriterion("station_id <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(Integer value) {
            addCriterion("station_id <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<Integer> values) {
            addCriterion("station_id in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<Integer> values) {
            addCriterion("station_id not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(Integer value1, Integer value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNull() {
            addCriterion("station_name is null");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNotNull() {
            addCriterion("station_name is not null");
            return (Criteria) this;
        }

        public Criteria andStationNameEqualTo(String value) {
            addCriterion("station_name =", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotEqualTo(String value) {
            addCriterion("station_name <>", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThan(String value) {
            addCriterion("station_name >", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThanOrEqualTo(String value) {
            addCriterion("station_name >=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThan(String value) {
            addCriterion("station_name <", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThanOrEqualTo(String value) {
            addCriterion("station_name <=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLike(String value) {
            addCriterion("station_name like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotLike(String value) {
            addCriterion("station_name not like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameIn(List<String> values) {
            addCriterion("station_name in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotIn(List<String> values) {
            addCriterion("station_name not in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameBetween(String value1, String value2) {
            addCriterion("station_name between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotBetween(String value1, String value2) {
            addCriterion("station_name not between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationCoordIsNull() {
            addCriterion("station_coord is null");
            return (Criteria) this;
        }

        public Criteria andStationCoordIsNotNull() {
            addCriterion("station_coord is not null");
            return (Criteria) this;
        }

        public Criteria andStationCoordEqualTo(String value) {
            addCriterion("station_coord =", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordNotEqualTo(String value) {
            addCriterion("station_coord <>", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordGreaterThan(String value) {
            addCriterion("station_coord >", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordGreaterThanOrEqualTo(String value) {
            addCriterion("station_coord >=", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordLessThan(String value) {
            addCriterion("station_coord <", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordLessThanOrEqualTo(String value) {
            addCriterion("station_coord <=", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordLike(String value) {
            addCriterion("station_coord like", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordNotLike(String value) {
            addCriterion("station_coord not like", value, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordIn(List<String> values) {
            addCriterion("station_coord in", values, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordNotIn(List<String> values) {
            addCriterion("station_coord not in", values, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordBetween(String value1, String value2) {
            addCriterion("station_coord between", value1, value2, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationCoordNotBetween(String value1, String value2) {
            addCriterion("station_coord not between", value1, value2, "stationCoord");
            return (Criteria) this;
        }

        public Criteria andStationStatusIsNull() {
            addCriterion("station_status is null");
            return (Criteria) this;
        }

        public Criteria andStationStatusIsNotNull() {
            addCriterion("station_status is not null");
            return (Criteria) this;
        }

        public Criteria andStationStatusEqualTo(Integer value) {
            addCriterion("station_status =", value, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusNotEqualTo(Integer value) {
            addCriterion("station_status <>", value, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusGreaterThan(Integer value) {
            addCriterion("station_status >", value, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("station_status >=", value, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusLessThan(Integer value) {
            addCriterion("station_status <", value, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusLessThanOrEqualTo(Integer value) {
            addCriterion("station_status <=", value, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusIn(List<Integer> values) {
            addCriterion("station_status in", values, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusNotIn(List<Integer> values) {
            addCriterion("station_status not in", values, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusBetween(Integer value1, Integer value2) {
            addCriterion("station_status between", value1, value2, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("station_status not between", value1, value2, "stationStatus");
            return (Criteria) this;
        }

        public Criteria andStationDescribeIsNull() {
            addCriterion("station_describe is null");
            return (Criteria) this;
        }

        public Criteria andStationDescribeIsNotNull() {
            addCriterion("station_describe is not null");
            return (Criteria) this;
        }

        public Criteria andStationDescribeEqualTo(String value) {
            addCriterion("station_describe =", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeNotEqualTo(String value) {
            addCriterion("station_describe <>", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeGreaterThan(String value) {
            addCriterion("station_describe >", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("station_describe >=", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeLessThan(String value) {
            addCriterion("station_describe <", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeLessThanOrEqualTo(String value) {
            addCriterion("station_describe <=", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeLike(String value) {
            addCriterion("station_describe like", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeNotLike(String value) {
            addCriterion("station_describe not like", value, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeIn(List<String> values) {
            addCriterion("station_describe in", values, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeNotIn(List<String> values) {
            addCriterion("station_describe not in", values, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeBetween(String value1, String value2) {
            addCriterion("station_describe between", value1, value2, "stationDescribe");
            return (Criteria) this;
        }

        public Criteria andStationDescribeNotBetween(String value1, String value2) {
            addCriterion("station_describe not between", value1, value2, "stationDescribe");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}