package com.wxbus.dao;

import com.wxbus.daomain.Helper;
import com.wxbus.daomain.HelperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int countByExample(HelperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int deleteByExample(HelperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer helpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int insert(Helper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int insertSelective(Helper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    List<Helper> selectByExample(HelperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    Helper selectByPrimaryKey(Integer helpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Helper record, @Param("example") HelperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Helper record, @Param("example") HelperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Helper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Helper record);
}