package com.wxbus.dao;

import com.wxbus.daomain.OverallConfig;
import com.wxbus.daomain.OverallConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OverallConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int countByExample(OverallConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int deleteByExample(OverallConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int insert(OverallConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int insertSelective(OverallConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    List<OverallConfig> selectByExample(OverallConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    OverallConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OverallConfig record, @Param("example") OverallConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OverallConfig record, @Param("example") OverallConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OverallConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OverallConfig record);
}