package com.wxbus.dao;

import com.wxbus.daomain.Passenger;
import com.wxbus.daomain.PassengerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PassengerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int countByExample(PassengerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int deleteByExample(PassengerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int insert(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int insertSelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    List<Passenger> selectByExample(PassengerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    Passenger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Passenger record, @Param("example") PassengerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Passenger record, @Param("example") PassengerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Passenger record);
}