package java.com.wxbus.dao;

import com.wxbus.daomain.DriverBusRoute;
import com.wxbus.daomain.DriverBusRouteExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DriverBusRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int countByExample(DriverBusRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int deleteByExample(DriverBusRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dBRId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int insert(DriverBusRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int insertSelective(DriverBusRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    List<DriverBusRoute> selectByExample(DriverBusRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    DriverBusRoute selectByPrimaryKey(Integer dBRId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DriverBusRoute record, @Param("example") DriverBusRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DriverBusRoute record, @Param("example") DriverBusRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DriverBusRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_bus_route
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DriverBusRoute record);
}